apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: 313368690603.dkr.ecr.eu-west-1.amazonaws.com/jenkins:3
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: shared-home
            mountPath: "/var/jenkins_home"
          - name: docker-sock-volume
            mountPath: "/var/run/docker.sock"
      volumes:
        - name: shared-home
          persistentVolumeClaim:
            claimName: efs-jenkins
        - name: docker-sock-volume
          hostPath:
            path: /var/run/docker.sock
            type: File

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-elb
spec:
  selector:
    app: jenkins
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
