apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      - system:masters
      rolearn: arn:aws:iam::313368690603:role/eksctl-ppro-nodegroup-standard-wo-NodeInstanceRole-1K4GKGUG639QA
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: 2019-05-20T13:52:48Z
  name: aws-auth
  namespace: kube-system
  resourceVersion: "901465"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 8d8d2a2f-7b06-11e9-a4f6-066fcdceff7a
