apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"wordpress"},"name":"wordpress-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"wordpress"}},"template":{"metadata":{"labels":{"app":"wordpress"}},"spec":{"containers":[{"image":"313368690603.dkr.ecr.eu-west-1.amazonaws.com/wordpress:2","name":"wordpress","ports":[{"containerPort":80}],"volumeMounts":[{"mountPath":"/var/www/html/wp_uploads","name":"efs-share"}]}],"volumes":[{"name":"efs-share","persistentVolumeClaim":{"claimName":"efs"}}]}}}}
  creationTimestamp: 2019-05-22T14:14:27Z
  generation: 10
  labels:
    app: wordpress
  name: wordpress-deployment
  namespace: default
  resourceVersion: "909498"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/wordpress-deployment
  uid: e8a1a157-7c9b-11e9-866a-0297a4fa8ce0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wordpress
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordpress
    spec:
      containers:
      - image: 313368690603.dkr.ecr.eu-west-1.amazonaws.com/wordpress:9
        imagePullPolicy: IfNotPresent
        name: wordpress
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html/wp_uploads
          name: efs-share
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: efs-share
        persistentVolumeClaim:
          claimName: efs
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-05-22T14:39:06Z
    lastUpdateTime: 2019-05-22T14:39:06Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-05-24T11:29:08Z
    lastUpdateTime: 2019-05-27T12:20:57Z
    message: ReplicaSet "wordpress-deployment-5f9d6f7669" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 10
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
